version: '3'

services:
  shadowsocks-libev:
    container_name: shadowsocks-libev
    image: liaoishere/shadowsocks-libev:latest
    ports:
      - 8880:8388/tcp
      - 8880:8388/udp
    environment:
      - PASSWORD=PASSWORD
      - ARGS=--plugin v2ray-plugin --plugin-opts server;host=vps.example.com;path=/v2ray -u
    restart: always

  shadowsocks-libev-tls:
    container_name: shadowsocks-libev-tls
    image: liaoishere/shadowsocks-libev:latest
    ports:
      - 8443:8388/tcp
      - 8443:8388/udp
    volumes:
      - /root/.acme.sh:/root/.acme.sh:ro
    environment:
      - PASSWORD=PASSWORD
      - ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=vps.example.com;path=/v2ray;cert=/root/.acme.sh/vps.example.com/vps.example.com.cer;key=/root/.acme.sh/vps.example.com/vps.example.com.key -u
    restart: always
