version: '3.7'

services:
  shadowsocks-libev:
    container_name: shadowsocks-libev
    image: liaoishere/shadowsocks-libev:latest
    ports:
      - 8880:8388/tcp
      - 8880:8388/udp
    environment:
      - PASSWORD=${PASSWORD}
      - ARGS=--plugin v2ray-plugin --plugin-opts server;host=${DOMAIN_NAME};path=/v2ray -u
    restart: always

  shadowsocks-libev-tls:
    container_name: shadowsocks-libev-tls
    image: liaoishere/shadowsocks-libev:latest
    depends_on:
      - acme-cron
    ports:
      - 8443:8388/tcp
      - 8443:8388/udp
    volumes:
      - cert:/cert:ro,nocopy
    environment:
      - PASSWORD=${PASSWORD}
      - ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=${DOMAIN_NAME};path=/v2ray;cert=/cert/${DOMAIN_NAME}/fullchain.cer;key=/cert/${DOMAIN_NAME}/${DOMAIN_NAME}.key -u
    restart: always

  v2ray-ws:
    container_name: v2ray-ws
    image: v2ray/official:latest
    depends_on:
      - acme-cron
    ports:
      - 8080:8080/tcp
    volumes:
      - cert:/cert:ro,nocopy
      - ${V2RAY_CONFIG}:/etc/v2ray/config.json
    restart: always

  caddy:
    container_name: caddy
    image: caddy/caddy
    depends_on:
      - acme-cron
    ports:
      - 443:443/tcp
      - 3000:3000/tcp
    volumes:
      - cert:/cert:ro,nocopy
      - ${CADDY_FILE}:/etc/caddy/Caddyfile
    restart: always

  acme-cron:
    container_name: acme-cron
    image: liaoishere/acme-cron
    volumes:
      - cert:/acme/data
    environment:
      - CF_Token=${CF_Token}
      - CF_Account_ID=${CF_Account_ID}
    restart: always

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ${GRAFANA_PROVISIONING_DIR}:/etc/grafana/provisioning
      - ${GRAFANA_DASHBOARD_DIR}:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: always

volumes:
  cert:
